core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from .views import home,service_version

app_name = 'home'

urlpatterns = [
    path('',home,name='home1'),
    path('version',service_version,name='service_version'),
]

home/models.py
from django.db import models


class MicroServices(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    version = models.CharField(max_length=100, null=True, blank=True)
    has_microui = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name + " | " + self.version + " | " + str(self.date)

class TrackMicroServiceVersion(models.Model):
    service = models.ForeignKey(MicroServices, on_delete=models.CASCADE)
    old_version = models.CharField(max_length=100, null=True, blank=True)
    new_version = models.CharField(max_length=100, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.service.name} ({self.old_version} -> {self.new_version}) on {self.date}'

home/views.py
import subprocess
from pathlib import Path
from django.shortcuts import render
from .models import MicroServices,TrackMicroServiceVersion
import os
import logging
logger = logging.getLogger(__name__)

BASE_DIR = Path(__file__).resolve().parent.parent


def home(request):
    services = MicroServices.objects.all()
    if request.method == 'POST':
        for service in services:
            name = request.POST.get(service.name)
            version = request.POST.get('service_version_{}'.format(service.id))
            if name and version:
                old_version = service.version
                service.version = version
                service.save()
                trackms = TrackMicroServiceVersion(service=service, old_version=old_version, new_version=version)
                trackms.save()
                logger.info("Service version updated: service_name=%s, old_version=%s, new_version=%s", service.name, old_version, version)
            else:
                logger.warning("Skipping service update: service_name=%s, service_version=%s", name, version)
    context = {
        'services': services,
    }
    return render(request, 'home/index.html', context)



def service_version(request):
    trackmicroservices = TrackMicroServiceVersion.objects.all().order_by('-date')
    context = {
        'trackmicroservices': trackmicroservices,
    }
    return render(request, 'home/service_version.html', context=context)

home/templates/home/index.html
{% extends "base/base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post">
                {% csrf_token %}
                <div class="row">
                    {% for service in services %}
                    {% if service.has_microui %}
                    <div class="col-4">
                        <div class="form-group">
                            <label for="{{service.name}}">Service Name </label>
                            <input type="text" class="form-control" name="{{service.name}}" id="{{service.id}}"
                                value="{{service.name}}">
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="service_version_{{ service.id }}">Service Version</label>
                            <input type="text" class="form-control" name="service_version_{{ service.id }}"
                                id="service_version_{{ service.id }}">
                        </div>
                    </div>
                    <div class="col-4 align-self-center">
                        <p>have MicroUI</p>
                    </div>
                    {% else %}
                    <div class="col-4">
                        <div class="form-group">
                            <label for="{{service.name}}">Service Name</label>
                            <input type="text" class="form-control" name="{{service.name}}" id="{{service.id}}"
                                value="{{service.name}}">
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="service_version_{{ service.id }}">Service Version</label>
                            <input type="text" class="form-control" name="service_version_{{ service.id }}"
                                id="service_version_{{ service.id }}">
                        </div>
                    </div>
                    <div class="col-4 align-self-center">
                        <p>doesn't have MicroUI</p>
                    </div>
                    {% endif %}
                    {%endfor%}
                </div>
                <button type="submit" class="btn btn-primary">Upgrade Service Version</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

home/templates/home/service_version.html
{% extends "base/base.html" %}
{% block content %}
<div class="container">
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Service Name</th>
        <th scope="col">Service Version</th>
        <th scope="col">Date</th>
        <th scope="col">Has Micro UI</th>
      </tr>
    </thead>
    <tbody>
        {% for trackmicroservice in trackmicroservices %}
      <tr>
        <th scope="row">{{ trackmicroservice.id }}</th>
        <td>{{ trackmicroservice.service.name }}</td>
        <td>{{ trackmicroservice.new_version }}</td>
        <td>{{ trackmicroservice.date }}</td>
        <td>{{ trackmicroservice.service.has_microui }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

templates/base/base.html
<!doctype html>
<html lang="tr">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

</head>

<body>
    {% include "base/snippets/navbar.html" %}
    {% block content %}

    {% endblock content %}
    {% include "base/snippets/footer.html" %}

    {% block script %}

    {% endblock script %}

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>

</body>

</html>

templates/base/snippets/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home:home1' %}">DevOps</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home:home1' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home:service_version' %}">Check Service Version!</a>
            </li>
        </ul>
      
    </div>
</nav>